use_frameworks!

platform :ios, '10.0'

target 'KwiksSystemsAlerts_Example' do
  pod 'KwiksSystemsAlerts', :path => '../'

  target 'KwiksSystemsAlerts_Tests' do
    inherit! :search_paths

    
  end
end
